WebApp/Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using WebApp.Data;
using WebApp.Models;
using System.IO.Pipelines;
using System.Collections.Generic;
using Bogus.DataSets;
using Microsoft.AspNetCore.Hosting;

namespace WebApp.Controllers
{
    public class PostsController : Controller
    {
        private readonly WebAppDbContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        [System.Obsolete]
        public PostsController(WebAppDbContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            this.hostingEnvironment = hostingEnvironment;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var post =  _context.Posts
                .Include(p => p.Category)
                .Include(p => p.District)
                .AsNoTracking();
            return View(await post.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        [HttpGet]
        [Authorize]
        public  IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["DistrictId"] = new SelectList(_context.Districts, "DistrictId", "DistrictName"); 
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("CategoryId,DistrictId,Title,Description,Images,PostFeatures,Contact")]  Post post)
        {
            
            if (ModelState.IsValid)
            {
                /* using (var ms = new MemoryStream())
                 {
                     await Images.CopyToAsync(ms);
                     var imagesByteArray = ms.ToArray();
                     Post.Image = imagesByteArray;
                     // var filePath = Path.GetTempFileName();
                     //  Images.CopyTo(ms);
                     //  post.Images = ms.CopyToAsync();
                 } */
               

                long size = Post.Images.Sum(f => f.Length);

                var filePaths = new List<string>();
                foreach (var formFile in Post.Images)
                {
                    if (formFile.Length > 0)
                    {
                        // full path to file in temp location
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "Images");
                        //var filePath = Path.GetTempFileName(); //we are using Temp file name just for the example. Add your own file path.
                        filePaths.Add(filePath);

                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                        }
                    }
                }

                _context.Add(post);          
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            } 
            return View(post);
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,DistrictId,Title,Description,Images,PostFeatures,Contact")] Post post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            _context.Posts.Remove(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CeylonFoot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--<link rel="stylesheet" href="~/css/site.css" /> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">  <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="~/font-awesome-4.7.0/css/font-awesome.min.css">                <!-- Font Awesome -->
    <link rel="stylesheet" href="css/bootstrap.min.css">                                      <!-- Bootstrap style -->
    <link rel="stylesheet" type="text/css" href="~/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="~/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="~/slick/slick-theme.css" />
    <link rel="stylesheet" href="~/css/templatemo-style.css">
</head>
<body>
    <div class="tm-main-content" id="top">
        <header>

            <div class="tm-top-bar-bg"></div>
            <div class="tm-top-bar" id="tm-top-bar">
                <div class="container">
                    <div class="row">
                        <nav class="navbar navbar-expand-lg narbar-light">
                            <a class="navbar-brand mr-auto" href="#">
                                <img src="img/logo.png">
                                Ceylon foot
                            </a>
                            <button type="button" id="nav-toggle" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#mainNav" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div id="mainNav" class="collapse navbar-collapse tm-bg-white">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link active" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#tm-section-2">Top Destinations</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#tm-section-3">Hotels</a>
                                    </li>
                                    <!--
                                    <li class="nav-item">
                                        <select asp-for="DistrictId" asp-items="ViewBag.DistrictId" class="custom-select">
                                            <option value="">Choose a District</option>
                                        </select>
                                    </li>
                                  <li class="nav-item">
        <a class="nav-link" href="#tm-section-4">Contact Us</a>
    </li>-->
                                    <!--  <li class="nav-item">
        <a class="nav-link text-uppercase btn-primary tm-btn" asp-controller="Posts" asp-action="Create">Add listing</a>
    </li> -->
                                </ul>
                            </div>
                            <div>
                                <partial name="_LoginPartial.cshtml" />
                            </div>
                           
                        </nav>
                    </div> <!-- row -->
                </div> <!-- container -->
            </div> <!-- .tm-top-bar -->
        </header>
        <div>
           
            <main>
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - CeylonFoot - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/js/jquery-1.11.3.min.js"></script>             <!-- jQuery (https://jquery.com/download/) -->
    <script src="~/js/popper.min.js"></script>                    <!-- https://popper.js.org/ -->
    <script src="~/js/bootstrap.min.js"></script>                 <!-- https://getbootstrap.com/ -->
    <script src="~/js/datepicker.min.js"></script>                <!-- https://github.com/qodesmith/datepicker -->
    <script src="~/js/jquery.singlePageNav.min.js"></script>      <!-- Single Page Nav (https://github.com/ChrisWojcik/single-page-nav) -->
    <script src="~/slick/slick.min.js"></script>                  <!-- http://kenwheeler.github.io/slick/ -->
    <script src="~/js/jquery.scrollTo.min.js"></script>

    <script>
        /* Google Maps
        ------------------------------------------------*/
        var map = '';
        var center;

        function initialize() {
            var mapOptions = {
                zoom: 16,
                center: new google.maps.LatLng(37.769725, -122.462154),
                scrollwheel: false
            };

            map = new google.maps.Map(document.getElementById('google-map'), mapOptions);

            google.maps.event.addDomListener(map, 'idle', function () {
                calculateCenter();
            });

            google.maps.event.addDomListener(window, 'resize', function () {
                map.setCenter(center);
            });
        }

        function calculateCenter() {
            center = map.getCenter();
        }

        function loadGoogleMap() {
            var script = document.createElement('script');
            script.type = 'text/javascript';
            script.src = 'https://maps.googleapis.com/maps/api/js?key=AIzaSyACDYn7a0nhQ8omMKQM4_zRBV71I8lI5bk&' + 'callback=initialize';
            document.body.appendChild(script);
        }

        /* DOM is ready
        ------------------------------------------------*/
        $(function () {

            // Change top navbar on scroll
            $(window).on("scroll", function () {
                if ($(window).scrollTop() > 100) {
                    $(".tm-top-bar").addClass("active");
                } else {
                    $(".tm-top-bar").removeClass("active");
                }
            });

            // Smooth scroll to search form
            $('.tm-down-arrow-link').click(function () {
                $.scrollTo('#tm-section-search', 300, { easing: 'linear' });
            });

            // Date Picker in Search form
            var pickerCheckIn = datepicker('#inputCheckIn');
            var pickerCheckOut = datepicker('#inputCheckOut');

            // Update nav links on scroll
            $('#tm-top-bar').singlePageNav({
                currentClass: 'active',
                offset: 60
            });

            // Close navbar after clicked
            $('.nav-link').click(function () {
                $('#mainNav').removeClass('show');
            });

            // Slick Carousel
            $('.tm-slideshow').slick({
                infinite: true,
                arrows: true,
                slidesToShow: 1,
                slidesToScroll: 1
            });

            loadGoogleMap();                                       // Google Map
            $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright
        });

    </script>

    @RenderSection("Scripts", required: false)

</body>
</html>